### ISSUE TITLE
Rare parsing errors

### ISSUE THREAD

**Issue by vladtcvs** [tempesta-tech/tempesta#950] opened 2018-03-12 01:43 UTC
running mixed_tests.test_mixed.HeadGetRequests and mixed_tests.test_mixed.RarelyUsedRequests (both contains HEAD requests) from master @ 7311971b289f9f6731cb4fb1b3a97dbf7f288b9c, sometimes I have such warnings:

`[tempesta] Warning: Parser error: state=Resp_HttpVer input=0x6e('nline documentat') data_len=238 off=0`

`[tempesta] Warning: Parser error: state=Resp_HttpVer input=0x6f('ont-family: Taho') data_len=476 off=0`

`[tempesta] Warning: Parser error: state=Resp_HttpVer input=0x20(' Tue, 05 Dec 201') data_len=102 off=0`

I have dumped messages between nginx and tempesta, and found that such substrings can be found exclusively as parts of headers or body of responses, such as `<p>For online documentation and support please refer to` or `Last-Modified: Tue, 05 Dec 2017 15:51:55 GMT`. I didn't find cases, where some part of data starts with `nline documentat` or smth like this.

This messages appeares very rare, compared to total number of requests, but I usually have few of them in the whole test.

**Comment by ikoveshnikov** [comment] 2018-03-12 06:19
duplicate of #871

**Closed by ikoveshnikov** 2018-03-12 06:19 UTC
Labels: bug
