### ISSUE TITLE
Incorrect string fixups in parser

### ISSUE THREAD

**Issue by byko3y** [tempesta-tech/tempesta#1547] opened 2022-01-11 15:46 UTC
# Scope

Recent modifications of tests uncovered some dormand bugs related to buffer fixups (chaining) in request parser: https://github.com/tempesta-tech/tempesta/commit/4c9d287c5e999d807048724459d7da7ca5bca2b6.  
This commit leads to additional 30 assertions in the tests (corrected by https://github.com/tempesta-tech/tempesta/pull/1546 ). That's because a single existing buffers test `TEST(http_parser, fills_hdr_tbl_for_req)` was errorneously disabled and now it is reenabled. However, there are most likely exist many other similar bugs related to the response parser and, most importantly, caching of responses.  
The chain of buffers produced by the parser is saved into cache storage instead of the original response buffer, so any corruptions to the response introduced by incorrect fixups will lead to invalid cached response.  

Also, there is a widespread misuse of `data-len` pair instead of `p-fsm_sz` in utility macroses:  
https://github.com/tempesta-tech/tempesta/blob/a6717348a69d47257b25afd2b68c776f5380675a/fw/http_parser.c#L274-L281   
https://github.com/tempesta-tech/tempesta/blob/a6717348a69d47257b25afd2b68c776f5380675a/fw/http_parser.c#L302-L307   
In many cases `data = len`, however, often it's not. For example, one of my recent pull requests trigger this problem: https://github.com/tempesta-tech/tempesta/pull/1539

# Testing

Need to implement more tests for buffers in the fw/t/unit/test_http_parser.c , similar to this one
https://github.com/tempesta-tech/tempesta/blob/a6717348a69d47257b25afd2b68c776f5380675a/fw/t/unit/test_http_parser.c#L765   
However, implementing those in C is tedious so it's better to implement more thorough testing in the tempesta-test/cache to verify all the headers and their values are preserved in the cached response.

**Comment by krizhanovsky** [comment] 2022-01-11 16:33
Could you also check the HTTP/2 parser - whether it has the same issues.

**Comment by krizhanovsky** [comment] 2022-01-12 15:47
Well, the things aren't so easy. Consider `RGen_Hdr` state, the first state for an HTTP header parsing. The first thing which the state does is `tfw_http_msg_hdr_open(msg, p)`, which sets `hm->stream->parser.hdr.data = p`, but doesn't touch the header string length. The unlikely parts of the macros are for the cases, when we reach the end of current data chunk and need more data for current state. `__msg_hdr_chunk_fixup()` has two paths:
1. the first chunk of the header (`TFW_STR_EMPTY(str)`) - we have `stra->data != NULL` thanks to `tfw_http_msg_hdr_open(msg, p)`, so we just define `str->len` as `data + len -p`, which is the correct computation for the length of the current chunk.
2. this is tricky: if `str` (the currently parsed HTTP field) isn't empty, then it means that we're parsing i'th chunk of the fields. Next, `data` is always contiguous memory area, which means that (i-1)'th chunk of the field is always a separate chunk of data, preceding the currently parsing `data`. This leads to that the whole `data` belongs to the header field.

The things are more complicated as described above because we store HTTP header name and fields in a separate TfwStr chunks and we have API to close/start the chunks.

It seems that the problem is more subtle. I'd expect that we do something invalid for a particular header parsing. Need to discuss exact test case and what we have parsed in which chunks for the test case.

*Please, as part of the task write a good comments on what's going on with the macros, how the heder open/fixup work, how the things work for header name vs field chunks in TfwStr. I.e. please properly document all your findings about handling HTTP strings in TfwStr trees.*

**Comment by byko3y** [comment] 2022-01-14 06:31
I looked through the code, and there seem to be two distinct styles of fixups:
- Lazily fixup when the chunk is exhausted i.e. __msg_hdr_chunk_fixup(data, len);
- Eagerly fixup every token.
As far as I see, there is a requirement for header names to be in a separate chunk, but I'm not aware of any such requirement for header values. And too many chunks means lower parser performance.

But anyways, there's still need for some more comments, which I'm going to write.

**Comment by krizhanovsky** [comment] 2022-02-16 16:36
Fixed with https://github.com/tempesta-tech/tempesta/pull/1566

**Closed by krizhanovsky** 2022-02-16 16:36 UTC
Labels: bug, http/1.1, cache
