### ISSUE TITLE
Missing functional tests for failovering

### ISSUE THREAD

**Issue by intelfx** [tempesta-tech/tempesta#812] opened 2017-08-22 15:39 UTC
We need more functional tests for correct handling of various failovering Tempesta config options:

- [ ] `server_connect_retries`
- [ ] `server_forward_retries`
- [ ] `server_forward_timeout`
- [ ] `server_retry_nonidempotent`
- [ ] `server_queue_size`

**Comment by krizhanovsky** [comment] 2017-08-27 18:21
Seems duplicate of #821

**Closed** 2017-08-27 18:24 UTC
Labels: duplicate, test
