### ISSUE TITLE
Exceeding space in case when there are a lot of clients

### ISSUE THREAD

**Issue by EvgeniiMekhanik** [tempesta-tech/tempesta#2191] opened 2024-08-01 09:54 UTC
When there are a lot of clients Tempesta FW fails to accept new connection and
writes in dmesg
```
145138.564405] [tdb] ERROR: Cannot allocate cache entry for key=0x7b284d0000000000
[145138.693617] [tdb] ERROR: out of free space
```
We should implement strategy to evict old clients time to time.

**Comment by krizhanovsky** [comment] 2024-08-01 14:52
Seems duplicate of #2000

**Closed** 2024-11-15 23:34 UTC
Labels: bug
