### ISSUE TITLE
[cfg] Make sure Tempesta doesn't specify itself as a backend

### ISSUE THREAD

**Issue by keshonok** [tempesta-tech/tempesta#774] opened 2017-07-26 17:31 UTC
A backend server (an IP address and port number) specified in Tempesta configuration may in fact turn out to be the same as an address where Tempesta listens to incoming requests from clients. The mistake is very easy to make. There should be a protection against that.

The problem was recognized before and seemingly fixed in 83c987fb. However, the fix has issues of its own.
* A listening address and port and  backend address and port may be specified in different forms. One may be specified as an IPv4 address, while the other may be specified as an IPv6 address. The function `tfw_addr_ifmatch()` that compares the addresses doesn't seem to handle this case. See issue #775.
* The check to see if the addresses of backend servers and Tempesta listeners match is performed after the configuration is processed by each module. However, the implementation details of configuration processing are that servers specified outside of any group are grouped together in the group named `default`, and that is done after complete configuration has been processed. So at the time the check is performed these servers are not in the configuration yet, so they are missed by the check.

The listener's module is called and initialized before the module that handles backends. Yet the check is implemented in the listener's module. Perhaps it makes more sense to move it to the module for backends.

**Comment by krizhanovsky** [comment] 2018-01-09 01:47
Most of Web accelearators don't care abut such kind of fool protection, so low priority.

**Comment by i-rinat** [comment] 2019-06-06 23:06
As mentioned in the description, the issue consists of two parts.

First is that the same address may be specified as IPv4 or as IPv4-mapped IPv6. That was described in issue #775, and was fixed by #1081. Now IPv6 is used to represent all addresses, thus normalizing them during configuration stage.

Last is about checking for matches at the very end of the configuration stage. That was fixed in somewhere near 6ff9bbabed5823028ca7a6814653fccdc550e4ab which was a part of https://github.com/tempesta-tech/tempesta/pull/851. That moved checking to the new stage which was called after all configuration was parsed.

With all above, I believe the issue is fixed already.

**Comment by krizhanovsky** [comment] 2019-06-06 23:49
If Tempesta doesn't start (or at least prints warnings) with configuration having the same address as listening and a upstream, then we can just close the issue. It'd be good to have a functional test (or just add the check to some existing test), but with that the issue is low priority it's not necessary.

**Comment by i-rinat** [comment] 2019-06-07 12:00
> If Tempesta doesn't start (or at least prints warnings) with configuration having the same address as listening and a upstream

It indeed doesn't start.
`./scripts/tempesta.sh --start` says:
```
Starting Tempesta...
...enable RPS on enp1s0
...load Tempesta modules
Loading Tempesta kernel modules...
Loading module tempesta_lib 
Loading module tempesta_tls 
Loading module tempesta_db 
Loading module tempesta_fw tfw_cfg_path=/root/tempesta/.settings/tempesta_fw.conf
...start Tempesta FW
Un-loading Tempesta kernel modules...
ERROR: cannot start Tempesta FW (sysctl code: Invalid argument)
```

dmesg output:
```
[ 2408.764955] [tdb] Start Tempesta DB
[ 2408.776415] net_ratelimit: 7 callbacks suppressed
[ 2408.776415] [tempesta fw] Initializing Tempesta FW kernel module...
[ 2408.781713] [tempesta fw] Registering new classifier: frang
[ 2408.784496] [tempesta fw] Registering new scheduler: hash
[ 2408.787215] [tempesta fw] Registering new scheduler: ratio
[ 2408.793992] [tempesta fw] Preparing for the configuration processing.
[ 2408.798905] [tempesta fw] ERROR: One of the backends is Tempesta itself! Please, fix the configuration.
[ 2408.803345] [tempesta fw] ERROR: Unable to complete the configuration of module 'sock_clnt': -22
[ 2408.807852] [tempesta fw] Warning: Configuration parsing has failed. Clean up...
[ 2408.818763] [tempesta fw] New configuration is cleaned.
[ 2408.822562] [tempesta fw] exiting...
[ 2408.824636] [tempesta fw] Un-registering scheduler: ratio
[ 2408.828506] [tempesta fw] Un-registering scheduler: hash
[ 2408.837757] [tempesta fw] Unregistering classifier: frang
[ 2408.866023] [tdb] Shutdown Tempesta DB
```

That's what happens when configuration below is used:
```
listen 81;
server 127.1.2.3:81;
```

**Comment by krizhanovsky** [comment] 2019-06-07 13:40
Not so bad, thanks!

**Closed by krizhanovsky** 2019-06-07 13:40 UTC
Labels: bug, low priority
