### ISSUE TITLE
BUG at http_limits.c:406

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#1404] opened 2020-04-22 18:08 UTC
## Scope

Just caught the BUG at current #1375 :
```
[  945.117448] kernel BUG at /root/tempesta/tempesta_fw/http_limits.c:406! 
[  945.120362] invalid opcode: 0000 [#1] SMP PTI
[  945.122355] Modules linked in: tempesta_fw(O) tempesta_db(O) tempesta_tls(O) tempesta_lib(O) binfmt_misc bochs_drm ttm drm_kms_helper drm crct10dif_pclmul fb_sys_fops syscopyarea ppdev sysfillrect sysimgblt parport_pc sg serio_raw parport button ip_tables x_tables ext4 crc16 mbcache jbd2 fscrypto sr_mod cdrom sd_mod ata_generic ata_piix libata psmouse i2c_piix4 e1000 scsi_mod [last unloaded: tempesta_lib]
[  945.133647] CPU: 1 PID: 0 Comm: swapper/1 Tainted: G           O    4.14.32-kdump+ #152
[  945.136338] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS ?-20190727_073836-buildvm-ppc64le-16.ppc.fedoraproject.org-3.fc31 04/01/2014
[  945.140970] task: ffff980e1d3f50c0 task.stack: ffff980e1c854000 
[  945.143251] RIP: 0010:frang_conn_close+0x31/0x40 [tempesta_fw]
[  945.145477] RSP: 0018:ffff980e3fd03e78 EFLAGS: 00010246 
[  945.148106] RAX: 0000000000000000 RBX: ffff980e3a405048 RCX: 000000000000091b
[  945.152067] RDX: 0000000000000001 RSI: 0000000000010080 RDI: ffff980e3a40504c
[  945.156196] RBP: ffff980e1c5f0dc0 R08: 00000000000027ec R09: 00000000000cce66
[  945.168760] R10: 0000000000000000 R11: 0000000000016346 R12: 0000000000000000
[  945.173241] R13: ffffffffae176710 R14: ffff980e1c5f0dc0 R15: 0000000000000001
[  945.178035] FS:  0000000000000000(0000) GS:ffff980e3fd00000(0000) knlGS:0000000000000000
[  945.187984] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  945.191919] CR2: 000055844ce1b3b8 CR3: 000000005500a003 CR4: 00000000003606e0
[  945.195778] Call Trace:
[  945.200544]  <IRQ>
[  945.203805]  security_sk_free+0x21/0x30
[  945.208724]  __sk_destruct+0xfa/0x140
[  945.213270]  call_timer_fn+0x2b/0x120
[  945.220684]  run_timer_softirq+0x1c5/0x3f0
[  945.224606]  ? __hrtimer_init+0x90/0x90
[  945.228663]  __do_softirq+0x104/0x297
[  945.233315]  irq_exit+0xa3/0xb0
[  945.237711]  smp_apic_timer_interrupt+0x6b/0x120
[  945.241018]  apic_timer_interrupt+0x7a/0x80
[  945.244017]  </IRQ>
```

Configuration:
```
listen 192.168.100.4:443 proto=https;

srv_group default {
	server 127.0.0.1:8080;
}
vhost debian {
	tls_certificate /root/tempesta/etc/tfw-root.crt;
	tls_certificate_key /root/tempesta/etc/tfw-root.key;

	proxy_pass default;
}

cache 0;
#cache_fulfill * *;

http_chain {
	-> debian;
}
```
tempesta-tech.com is serviced by Apache backend on the VM with Tempesta FW.

## Testing

I saw the bug only once and I'm not sure about exact scenario, but there are my actions:
1. run Tempesta with the same config, but `default` instead of `debian`
2. launch `tls-perf` on the loopback
3. restart Tempesta with the config above
4. visit index page of the site in the VM using Firefox and clich services
5. wait about a minute or two and the bug appeared.

**Comment by krizhanovsky** [comment] 2020-04-25 13:48
Just caught exactly the same crash in following scenario:
1. start Tempesta in 1 CPU VM with cache disabled
2. run tls-perf on the host system and stop it after about 50 seconds
3. restart Tempesta with the cache enabled in the configuration file
The crash happened exactly on the `--restart` action.

**Comment by krizhanovsky** [comment] 2020-06-23 19:24
I face the bug quite frequently, even on plain TLS performance tests with `tls-perf`

**Comment by krizhanovsky** [comment] 2020-08-05 17:46
Didn't see this for a while

**Comment by krizhanovsky** [comment] 2020-08-11 13:21
I didn't see the issue for a while and can not reproduce it for the whole today on current master. Probably that was a #1375 specific issue.

**Comment by krizhanovsky** [comment] 2020-08-11 13:26
Since @ikoveshnikov you've seen it, please update the task with a scenario how to reproduce it.

**Comment by ikoveshnikov** [comment] 2020-08-17 06:51
I've seen the issue when i was debugging #1435  and #1431 while I was sending random and infrequent `curl` requests with `connection: close` header. All these bugs are reproduced in mostly the same case, but it seems that exact behaviour depends on  frequency of requests an exact state of Tempesta/Kernel buffers. Since I'm the only one who have seen the issue for a long time and since all the mentioned bugs are already assigned to me, I will handle this one too.

**Comment by i-rinat** [comment] 2020-09-14 20:56
Got this too on current master (a83321549229d620b8dd45c75a633c7dadae7b75). Same place in the code, but with a bit different backtrace.
```
[ 6041.752250] ------------[ cut here ]------------
[ 6041.756631] kernel BUG at /root/tempesta/tempesta_fw/http_limits.c:406!
[ 6041.761272] invalid opcode: 0000 [#1] SMP PTI
[ 6041.764537] Modules linked in: tempesta_fw(O) tempesta_db(O) tempesta_tls(O) tempesta_lib(O) sha256_mb mcryptd sha256_ssse3 sha512_ssse3 sha512_generic crc32_pclmul crc32c_intel ghash_clmulni_intel pcbc aesni_intel aes_x86_64 crypto_simd glue_helper cryptd virtio_console virtio_balloon virtio_net virtio_pci virtio_ring virtio [last unloaded: tempesta_lib]
[ 6041.779539] CPU: 0 PID: 0 Comm: swapper/0 Tainted: G           O    4.14.32-tfw-debug #0.0.0
[ 6041.782921] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 1.14.0-1 04/01/2014
[ 6041.786220] task: ffffffff82210480 task.stack: ffffffff82200000
[ 6041.788552] RIP: 0010:frang_conn_close+0x31/0x40 [tempesta_fw]
[ 6041.790683] RSP: 0018:ffff88017fc03ce0 EFLAGS: 00010246
[ 6041.792820] RAX: 0000000000000000 RBX: ffff880168409048 RCX: 0000000000000044
[ 6041.796188] RDX: 0000000000000001 RSI: 0000000000010080 RDI: ffff88016840904c
[ 6041.799177] RBP: ffff88013ac72a80 R08: ffff880157fefc00 R09: 0000000180100008
[ 6041.803084] R10: ffff88017fc03c20 R11: 0000000000000000 R12: 0000000000000000
[ 6041.805667] R13: ffff88013a5e0262 R14: ffff880159170078 R15: ffff88013ac72a80
[ 6041.808245] FS:  0000000000000000(0000) GS:ffff88017fc00000(0000) knlGS:0000000000000000
[ 6041.825017] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 6041.827182] CR2: 00007f499aa4b018 CR3: 000000000220a006 CR4: 00000000003606f0
[ 6041.829609] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[ 6041.832954] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[ 6041.835242] Call Trace:
[ 6041.836557]  <IRQ>
[ 6041.837772]  security_sk_free+0x21/0x30
[ 6041.839751]  __sk_destruct+0xf2/0x140
[ 6041.841761]  tcp_v4_rcv+0x8df/0x9b0
[ 6041.843621]  ip_local_deliver_finish+0x6b/0x190
[ 6041.845937]  ip_local_deliver+0x56/0xc0
[ 6041.847736]  ? ip_rcv_finish+0x340/0x340
[ 6041.849386]  ip_rcv+0x24f/0x370
[ 6041.850908]  ? inet_del_offload+0x30/0x30
[ 6041.852867]  __netif_receive_skb_core+0x318/0xb00
[ 6041.855198]  ? __getnstimeofday64+0x39/0xd0
[ 6041.857057]  ? process_backlog+0x92/0x120
[ 6041.858717]  process_backlog+0x92/0x120
[ 6041.860672]  net_rx_action+0x23d/0x380
[ 6041.863788]  __do_softirq+0x104/0x297
[ 6041.865625]  irq_exit+0xa3/0xb0
[ 6041.867367]  call_function_single_interrupt+0x7a/0x80
[ 6041.869665]  </IRQ>
[ 6041.871080] RIP: 0010:default_idle+0x12/0xf0
[ 6041.873154] RSP: 0018:ffffffff82203ec0 EFLAGS: 00000246 ORIG_RAX: ffffffffffffff04
[ 6041.876624] RAX: ffffffff819680c0 RBX: ffffffff82210480 RCX: 0000000000000000
[ 6041.879042] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 0000000000000000
[ 6041.881371] RBP: 0000000000000000 R08: 0000058272f6a898 R09: ffff880157f1a900
[ 6041.884109] R10: 0000000000000000 R11: 000005e51a9e2e13 R12: ffffffff82210480
[ 6041.886997] R13: ffffffff82210480 R14: 0000000000000000 R15: 0000000000000000
[ 6041.889515]  ? __sched_text_end+0x6/0x6
[ 6041.891299]  do_idle+0x156/0x1b0
[ 6041.894545]  cpu_startup_entry+0x14/0x20
[ 6041.896486]  start_kernel+0x3dc/0x3e4
[ 6041.898452]  secondary_startup_64+0xa5/0xb0
[ 6041.900372] Code: 00 00 48 85 db 74 22 48 8d 7b 04 e8 ca 46 78 c1 8b 03 85 c0 74 15 83 e8 01 89 03 c6 43 04 00 48 8d 7b d0 5b e9 71 46 00 00 0f 0b <0f> 0b 0f 1f 00 66 2e 0f 1f 84 00 00 00 00 00 0f 0b 0f 1f 40 00 
[ 6041.907748] RIP: frang_conn_close+0x31/0x40 [tempesta_fw] RSP: ffff88017fc03ce0
[ 6041.911061] ---[ end trace e068978b501c591f ]---
[ 6041.913007] Kernel panic - not syncing: Fatal exception in interrupt
[ 6041.915759] Kernel Offset: disabled
[ 6041.917588] ---[ end Kernel panic - not syncing: Fatal exception in interrupt
```

```
cache 1;
cache_fulfill * *;

listen 443 proto=https;
listen 80;
tls_certificate /root/tempesta/.settings/tfw-root.crt;
tls_certificate_key /root/tempesta/.settings/tfw-root.key;

sticky {
    cookie enforce;
    js_challenge resp_code=503 delay_min=1000 delay_range=1500
                 delay_limit=3000 /root/tempesta/.settings/js_challenge.html;
}

# Default values from from /etc/tempesta_fw.conf.
frang_limits {
    request_rate 20;
    request_burst 15;
    connection_rate 8;
    connection_burst 6;
    concurrent_connections 8;
    client_header_timeout 20;
    client_body_timeout 10;
    http_uri_len 1024;
    http_field_len 256;
    http_ct_required false;
    http_methods get post head;
    http_ct_vals "text/plain" "text/html";
    http_header_chunk_cnt 10;
    http_body_chunk_cnt 0;
    http_resp_code_block 403 404 502 20 5;
}

srv_group srv_grp1 {
    server 192.168.122.1:80;
}
srv_group default {
    server 192.168.122.1:80;
}
vhost tempesta.local {
    # Apache2 backend.
    proxy_pass srv_grp1;
}
vhost default {
    proxy_pass default;
}
```

Encountered while simulating browser connections with:
```python
import time
import selenium
import selenium.webdriver

driver = selenium.webdriver.Firefox()

try:
    for k in range(1_000_000):
        try:
            driver.get('https://tempesta.local/?try={}'.format(k))
        except selenium.common.exceptions.WebDriverException:
            pass
        time.sleep(3)
        driver.delete_all_cookies()
finally:
    driver.quit()
```

It's rare. Increasing number of parallel clients doesn't make it happen more often.

**Comment by krizhanovsky** [comment] 2020-10-06 15:19
Just caught the bug again on
```
$ ./wrk -c 1000 -d 10 -t 2 'http://192.168.100.4/searchresults.en-us.html?aid=304142&label=gen173nr-1FCAEoggI46AdIM1gEaIkCiAEBmAExuAEZyAEP2AEB6AEB-AECiAIBqAIDuAKAg4DkBcACAQ&sid=686a0975e8124342396dbc1b331fab24&tmpl=searchresults&ac_click_type=b&ac_position=0&checkin_month=3&checkin_monthday=7&checkin_year=2019&checkout_month=3&checkout_monthday=10&checkout_year=2019&class_interval=1&dest_id=20015107&dest_type=city&dtdisc=0&from_sf=1&group_adults=1&group_children=0&inac=0&index_postcard=0&label_click=undef&no_rooms=1&postcard=0&raw_dest_type=city&room1=A&sb_price_type=total&sb_travel_purpose=business&search_selected=1&shw_aparth=1&slp_r_match=0&src=index&srpvid=e0267a2be8ef0020&ss=Pasadena%2C%20California%2C%20USA&ss_all=0&ss_raw=pasadena&ssb=empty&sshis=0&nflt=hotelfacility%3D107%3Bmealplan%3D1%3Bpri%3D4%3Bpri%3D3%3Bclass%3D4%3Bclass%3D5%3Bpopular_activities%3D55%3Bhr_24%3D8%3Btdb%3D3%3Breview_score%3D70%3Broomfacility%3D75%3B&rsf='
```

**Comment by krizhanovsky** [comment] 2020-11-08 13:53
The bug has a workaround:
```C
--- a/tempesta_fw/http_limits.c
+++ b/tempesta_fw/http_limits.c
@@ -403,7 +403,12 @@ frang_conn_close(struct sock *sk)
 
        spin_lock(&ra->lock);
 
-       BUG_ON(!ra->conn_curr);
+       //BUG_ON(!ra->conn_curr);
+       if (!ra->conn_curr) {
+               spin_unlock(&ra->lock);
+               return;
+       }
+
        ra->conn_curr--;
 
        spin_unlock(&ra->lock);
```

**Comment by krizhanovsky** [comment] 2020-12-22 22:38
Just hit the crash once more on current master as of 95dddf4768f2f6ad9e41fa64705c5904bdf09f13 on our TLS test suite.

**Comment by krizhanovsky** [comment] 2021-02-13 20:34
Just hit a strange memory corruption on running the full test suite with verbosity 1 and on 4 CPU VM. The crash happened on `pipelining.test_pipelining.PipeliningTestFI` test.
```
[ 1182.302609] Start test: pipelining.test_pipelining.PipeliningTestFI.test_failovering
[ 1183.319369] [tdb] Start Tempesta DB
[ 1183.409380] [tempesta fw] Initializing Tempesta FW kernel module...
[ 1183.558705] [tempesta fw] Warning: Listening for HTTP/1.1 protocol is compatibility mode and may lack of performance.
[ 1183.566224] [tempesta fw] Configuration processing is completed.
[ 1183.638781] [tdb] Opened table /opt/tempesta/db/filter.tdb: size=16777216 rec_size=20 base=ffff88006c400000
[ 1183.770398] [tdb] Opened table /opt/tempesta/db/sessions.tdb: size=16777216 rec_size=360 base=ffff88006b400000
[ 1183.797411] [tdb] Opened table /opt/tempesta/db/client.tdb: size=16777216 rec_size=984 base=ffff88006a400000
[ 1183.804446] [tempesta fw] Open listen socket on: 0.0.0.0
[ 1183.846662] [tempesta fw] modules are started
[ 1313.091190] general protection fault: 0000 [#1] SMP KASAN PTI
[ 1313.096764] Modules linked in: stap_tempesta(O+) tempesta_fw(O) tempesta_db(O) tempesta_tls(O) tempesta_lib(O) crct10dif_pclmul ppdev bochs_drm ttm drm_kms_helper intel_rapl_perf drm sg fb_sys_fops syscopyarea sysfillrect parport_pc sysimgblt parport serio_raw button binfmt_misc ip_tables x_tables ext4 crc16 mbcache jbd2 fscrypto sd_mod sr_mod cdrom ata_generic virtio_net ata_piix psmouse libata virtio_pci scsi_mod virtio_ring i2c_piix4 virtio [last unloaded: tempesta_lib]
[ 1313.098600] CPU: 1 PID: 20795 Comm: staprun Tainted: G           O    4.14.32-kdump+ #181
[ 1313.098600] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.13.0-3.fc33 04/01/2014
[ 1313.098600] task: ffff880032974240 task.stack: ffff88004c988000
[ 1313.098600] RIP: 0010:memset_erms+0x9/0x10
[ 1313.098600] RSP: 0018:ffff88004c98faf8 EFLAGS: 00010202
[ 1313.098600] RAX: 1ffffffff8138d00 RBX: fffffbfff8138d08 RCX: 1ffffffff8138d08
[ 1313.098600] RDX: 1ffffffff8138d08 RSI: 0000000000000000 RDI: dffffc0000000000
[ 1313.098600] RBP: ffffffffc09c6840 R08: 0000000000000000 R09: dffffc0000000000
[ 1313.098600] R10: 0000000000000000 R11: fffffbfff09569d7 R12: ffffffffc09c1e80
[ 1313.098600] R13: ffffffffc09c683f R14: 0000000000000002 R15: ffffffffc09c1eb8
[ 1313.098600] FS:  00007f61d75c3240(0000) GS:ffff88006d480000(0000) knlGS:0000000000000000
[ 1313.098600] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 1313.098600] CR2: 000056149cf1c098 CR3: 000000003159c006 CR4: 00000000003606e0
[ 1313.098600] Call Trace:
[ 1313.098600]  kasan_unpoison_shadow+0x30/0x40
[ 1313.098600]  __asan_register_globals+0x4e/0x90
[ 1313.098600]  do_init_module+0xc8/0x2ff
[ 1313.098600]  load_module+0x263f/0x30a0
[ 1313.098600]  ? layout_and_allocate+0x15b0/0x15b0
[ 1313.098600]  ? __vmalloc_node_range+0x29a/0x360
[ 1313.098600]  ? check_stack_object+0x1d/0x60
[ 1313.098600]  ? SYSC_init_module+0x198/0x1b0
[ 1313.098600]  SYSC_init_module+0x198/0x1b0
[ 1313.098600]  ? load_module+0x30a0/0x30a0
[ 1313.098600]  ? SYSC_finit_module+0x170/0x170
[ 1313.098600]  do_syscall_64+0xeb/0x240
[ 1313.098600]  entry_SYSCALL_64_after_hwframe+0x42/0xb7
[ 1313.098600] RIP: 0033:0x7f61d790feca
[ 1313.098600] RSP: 002b:00007fff06ee03e8 EFLAGS: 00000206 ORIG_RAX: 00000000000000af
[ 1313.098600] RAX: ffffffffffffffda RBX: 0000000000000003 RCX: 00007f61d790feca
[ 1313.098600] RDX: 000056149cf1afc0 RSI: 0000000000030980 RDI: 00007f61d758f010
[ 1313.098600] RBP: 00007f61d75c3198 R08: 0000000000000000 R09: 0000000000000001
[ 1313.098600] R10: 00000000ffffff00 R11: 0000000000000206 R12: 00007f61d758f010
[ 1313.098600] R13: 0000000000000000 R14: 000056149cf1afc0 R15: 00007fff06ee04a0
[ 1313.098600] Code: 48 c1 e9 03 40 0f b6 f6 48 b8 01 01 01 01 01 01 01 01 48 0f af c6 f3 48 ab 89 d1 f3 aa 4c 89 c8 c3 90 49 89 f9 40 88 f0 48 89 d1 <f3> aa 4c 89 c8 c3 90 49 89 fa 40 0f b6 ce 48 b8 01 01 01 01 01
[ 1313.098600] RIP: memset_erms+0x9/0x10 RSP: ffff88004c98faf8
```
So probably the original problem is in a memory corruption, which just corrupted the Frang data structures.

**Comment by krizhanovsky** [comment] 2021-05-02 20:40
`crash` shows that the `magic` for spin lock `ra->lock` is 0, which is definitely wrong - it must be `SPINLOCK_MAGIC = 0xdead4ead` (the `BUG_ON()` happens with the spin lock acquired). It seems this is `bzero_fast()`'ed expired entry.

Next, with this patch
```diff
--- a/tempesta_fw/http_limits.c
+++ b/tempesta_fw/http_limits.c
@@ -402,22 +402,20 @@ frang_conn_close(struct sock *sk)
        FrangAcc *ra = sk->sk_security;
 
        BUG_ON(!ra);
+       BUG_ON((long)ra == 0xdeadbeef);
 
        spin_lock(&ra->lock);
-#if 0
+
        BUG_ON(!ra->conn_curr);
-#else
-       /* TODO #1404 temporal workaround. */
-       if (!ra->conn_curr) {
-               spin_unlock(&ra->lock);
-               return;
-       }
-#endif
+
        ra->conn_curr--;
 
        spin_unlock(&ra->lock);
 
        tfw_client_put(FRANG_ACC2CLI(ra));
+
+       sk->sk_security = (void *)0xdeadbeef;
 }
 
 static int
```
I observed crash
```
[  311.336988] [tdb] Shutdown Tempesta DB
[  311.343130] BUG: unable to handle kernel paging request at ffffffffc06ce5c0
[  311.352694] IP: 0xffffffffc06ce5c0
[  311.355311] PGD fe12067 P4D fe12067 PUD fe14067 PMD 4eadc067 PTE 0
[  311.358779] Oops: 0010 [#1] SMP PTI
[  311.361087] Modules linked in: tempesta_db(O-) tempesta_tls(O) tempesta_lib(O) bochs_drm ttm crct10dif_pclmul drm_kms_helper intel_rapl_perf ppdev drm sg serio_raw fb_sys_fops syscopyarea sysfillrect sysimgblt parport_pc parport button binfmt_misc ip_tables x_tables ext4 crc16 mbcache jbd2 fscrypto sr_mod cdrom sd_mod ata_generic virtio_net ata_piix psmouse virtio_pci virtio_ring virtio i2c_piix4 libata scsi_mod [last unloaded: tempesta_db]
[  311.379996] CPU: 0 PID: 7 Comm: ksoftirqd/0 Tainted: G           O    4.14.32-kdump+ #217
[  311.383208] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.13.0-3.fc33 04/01/2014
[  311.386617] task: ffff8c9e9c8241c0 task.stack: ffffb62d00370000
[  311.389431] RIP: 0010:0xffffffffc06ce5c0
[  311.391542] RSP: 0018:ffffb62d00373cc0 EFLAGS: 00010206
[  311.394477] RAX: 0000000000000017 RBX: 00000000000005a8 RCX: ffffffffc06ce5c0
[  311.397694] RDX: 0000000000000586 RSI: ffff8c9e9bcd7600 RDI: ffff8c9e99c3a840
[  311.400720] RBP: 0000000000000002 R08: 0000000000040000 R09: 0000000000002e27
[  311.403662] R10: 0000000000000001 R11: 0000000000000000 R12: ffff8c9e99c3a840
[  311.407704] R13: 0000000000000000 R14: ffff8c9e9bcd7600 R15: 0000000000000586
[  311.411370] FS:  0000000000000000(0000) GS:ffff8c9ebfc00000(0000) knlGS:0000000000000000
[  311.414442] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  311.416998] CR2: ffffffffc06ce5c0 CR3: 000000000fe10005 CR4: 00000000003606f0
[  311.420217] Call Trace:
[  311.422239]  ? tcp_write_xmit+0x41f/0x1190
[  311.424256]  ? tcp_write_timer_handler+0x230/0x230
```
Get the problem line:
```
# addr2line -e vmlinux -i $(perl -e 'printf("%x\n", 0x'$(nm vmlinux|grep '\<tcp_write_xmit\>'|awk '{print $1}')'+0x41f)')
/root/linux-4.14.32-tfw/net/ipv4/tcp_output.c:2399
```
and this line is under `if (sk->sk_write_xmit && tempesta_tls_skb_type(skb))` condition. I.e. when TDB clients table is closed, the TCP stack still processes Tempesta sockets.

In fact, ` ss_active_guard_exit()` is responsible for closing sockets only, so the half closed sockets can exist in the system for a while even after full Tempesta modules unloading.

**Closed** 2021-05-04 17:51 UTC
Labels: bug
