### ISSUE TITLE
Tempesta before Wordpress - Parser errors

### ISSUE THREAD

**Issue by pale-emperor** [tempesta-tech/tempesta#1768] opened 2022-12-13 15:37 UTC
# Motivation

Now we faced into problem:

In case we placed tempesta between client and Wordpress site like shown below:
---------------            ---------------               ---------------
|       client       | ---->  |    tempesta   |   ---->    |   wordpress  |
---------------            ---------------               ---------------
We have a problem while site open

Dmesg provided:
```
Mozilla:
[366961.061185] [tempesta fw] Warning: Parser error: state=Req_HdrCookieV input(-8)=0x67('Cookie: gdpr[consent_types]=%5B%22privacy-policy') data_len=791 off=30
[366961.061452] [tempesta fw] Warning: failed to parse request: 3.72.94.204

Safari:
[367344.404217] [tempesta fw] Warning: Parser error: state=Req_HdrCookieV input(-8)=0x77('Cookie: wp-settings-time-1=1670937305; redux_cur') data_len=305 off=122
[367344.404492] [tempesta fw] Warning: failed to parse request: 3.72.94.204

Chrome (works fine until we try to login into WP admin panel)
[367545.333798] [tempesta fw] Warning: Parser error: state=Resp_HdrSet_CookieV input(-8)=0x77('Cookie: wordpress_ccd260231e5cea4d0d9daa') data_len=318 off=286
[367545.334020] [tempesta fw] Warning: response dropped: processing error: 3.72.94.204

```

# Testing

To reproduce you can setup tempesta-fw as reverse-proxy to our wordpress site

# Documentation
Tempesta-fw config:

```
listen 443 proto=https;

srv_group default {
	server 10.0.3.190:80; # local wordpress site in container
}

vhost tempesta-tech.com {
	tls_certificate /root/tempesta/etc/fullchain.pem;
	tls_certificate_key /root/tempesta/etc/privkey.pem;

	proxy_pass default;
}

http_chain {
	-> tempesta-tech.com;
}
```

**Comment by krizhanovsky** [comment] 2022-12-15 15:42
duplicate of #1690

**Closed by krizhanovsky** 2022-12-15 15:42 UTC
Labels: bug, duplicate, crucial
