### ISSUE TITLE
Flacky test t_stress.test_header_leak.TestH2HeaderLeak (seems invalid framing in Tempesta)

### ISSUE THREAD

**Issue by EvgeniiMekhanik** [tempesta-tech/tempesta#2264] opened 2024-10-16 19:00 UTC
t_stress.test_header_leak.TestH2HeaderLeak failed on remote CI:
Traceback (most recent call last):
```
  File "/home/jenkins/workspace/_PR_tempesta_PR-2253/tempesta-test/framework/deproxy_manager.py", line 34, in run_deproxy_server

    poll_fun()

  File "/usr/lib/python3.10/asyncore.py", line 195, in poll2

    readwrite(obj, flags)

  File "/usr/lib/python3.10/asyncore.py", line 130, in readwrite

    obj.handle_error()

  File "/home/jenkins/workspace/_PR_tempesta_PR-2253/tempesta-test/helpers/deproxy.py", line 1133, in handle_error

    error.bug("\tDeproxy: Client: %s" % v)

  File "/home/jenkins/workspace/_PR_tempesta_PR-2253/tempesta-test/helpers/error.py", line 82, in bug

    raise Error(msg).with_traceback(exc_info[2])

  File "/usr/lib/python3.10/asyncore.py", line 115, in readwrite

    obj.handle_read_event()

  File "/usr/lib/python3.10/asyncore.py", line 427, in handle_read_event

    self.handle_read()

  File "/home/jenkins/workspace/_PR_tempesta_PR-2253/tempesta-test/framework/deproxy_client.py", line 624, in handle_read

    events = self.h2_connection.receive_data(self.response_buffer)

  File "/usr/local/lib/python3.10/dist-packages/h2/connection.py", line 1462, in receive_data

    for frame in self.incoming_buffer:

  File "/usr/local/lib/python3.10/dist-packages/h2/frame_buffer.py", line 153, in __next__

    f = self._update_header_buffer(f)

  File "/usr/local/lib/python3.10/dist-packages/h2/frame_buffer.py", line 88, in _update_header_buffer

    raise ProtocolError("Invalid frame during header block.")

helpers.error.Error: 	Deproxy: Client: Invalid frame during header block. (ProtocolError: Invalid frame during header block.)
```

In seems that this is not a flacky  test, but error in Tempesta Code

**Comment by krizhanovsky** [comment] 2024-10-17 15:25
Probably a duplicate of #2181, but not necessary...

**Closed** 2024-12-09 16:26 UTC
Labels: bug
