### ISSUE TITLE
Excessive logs in dmesg

### ISSUE THREAD

**Issue by KonsKo** [tempesta-tech/tempesta#2254] opened 2024-09-27 16:02 UTC
# Motivation

Working with the SUT server, some tests produce a lot of excessive repeatable logs.

# Scope

Run whole test suite on the SUT server or particular test (for example, `t_reconf.test_stress_sched_hash.TestSchedHashLiveReconf.test_reconf_on_the_fly_for_hash_sched`, there are more tests BTW 
 with the same huge logs).
 Currently, this particular test is failed.
 Look at the dmesg.
 There will be a lot of the same logs :
 
![Screenshot 2024-09-27 at 9 00 48 AM](https://github.com/user-attachments/assets/71ded77a-2af1-4c39-bcde-231e46abc836)

# Testing

For example: `t_reconf.test_stress_sched_hash.TestSchedHashLiveReconf.test_reconf_on_the_fly_for_hash_sched`

**Comment by krizhanovsky** [comment] 2024-10-14 16:29
Probably fixed in https://github.com/tempesta-tech/tempesta/pull/2239 , @KonsKo could you please test that the problem is gone?

**Comment by KonsKo** [comment] 2024-10-15 15:22
Looks like the problem has gone
```
[63896.519122] Start test: t_reconf.test_stress_sched_hash.TestSchedHashLiveReconf.test_reconf_on_the_fly_for_hash_sched
[63899.768446] [tdb] Start Tempesta DB
[63899.805442] net_ratelimit: 11 callbacks suppressed
[63899.805443] [tempesta fw] Initializing Tempesta FW kernel module...
[63899.994846] [tempesta fw] Warning: Vhost default doesn't have certificate with matching SAN/CN.
                   Maybe that's fine, but it's worth checking the
                   config - if there is no relations between the
                   names, then host name confusion attack is possible.
[63900.063460] [tempesta fw] Configuration processing is completed.
[63900.112487] [tdb] Opened table /opt/tempesta/db/filter0.tdb: size=16777216 rec_size=20 base=0000000031e8f88e
[63900.137279] [tdb] Opened table /opt/tempesta/db/sessions0.tdb: size=16777216 rec_size=312 base=000000009d72e694
[63900.164182] [tdb] Opened table /opt/tempesta/db/client0.tdb: size=16777216 rec_size=624 base=000000009d697641
[63900.181989] [tempesta fw] Open listen socket on: 127.0.0.1:443
[63900.218642] [tempesta fw] Tempesta FW is ready
[63910.314628] [tempesta tls] Warning: Cannot send TLS alert 0:1, -9
[63910.321295] [tempesta fw] Warning: Close TCP socket w/o sending alert to the peer: 127.0.0.1
[63911.194957] [tempesta fw] Live reconfiguration of Tempesta.
[63911.238830] [tempesta fw] Warning: Vhost default doesn't have certificate with matching SAN/CN.
                   Maybe that's fine, but it's worth checking the
                   config - if there is no relations between the
                   names, then host name confusion attack is possible.
[63911.276095] [tempesta fw] Configuration processing is completed.
[63911.550663] [tempesta fw] Tempesta FW is ready
[63921.715103] [tempesta tls] Warning: Cannot send TLS alert 0:1, -9
[63921.721759] [tempesta fw] Warning: Close TCP socket w/o sending alert to the peer: 127.0.0.1
[63925.006967] [tdb] Close table 'client0.tdb'
[63925.024094] [tdb] Close table 'sessions0.tdb'
[63925.090192] [tdb] Close table 'filter0.tdb'
[63925.094984] [tempesta fw] modules are stopped
[63925.126061] [tempesta fw] exiting...
[63925.210884] [tdb] Shutdown Tempesta DB
[63925.396228] End test:   t_reconf.test_stress_sched_hash.TestSchedHashLiveReconf.test_reconf_on_the_fly_for_hash_sched
```

**Closed** 2024-10-15 16:10 UTC
Labels: good to start
