### ISSUE TITLE
BUG on invalid response 

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#816] opened 2017-08-23 16:26 UTC
The bug is reported by @bartolootrit . An adjusted deproxy test returns an invalid response as

```
HTTP/1.1 204 No Content
Content-type: text/html
Connection: keep-alive
Content-Length: 138
Last-Modified: Mon, 12 Dec 2016 13:59:39 GMT
Server: Deproxy Server
Date: Wed, 23 Aug 2017 11:56:18 GMT
<html>
<head>
    <title>An Example Page</title>
</head>
<body>
    Hello World, this is a very simple HTML document.
</body>
</html>
```

making Tempesta crash at https://github.com/tempesta-tech/tempesta/blob/master/tempesta_fw/http.c#L2478

**Comment by krizhanovsky** [comment] 2017-08-23 16:45
@intelfx please add appropriate test to your scope.

**Comment by intelfx** [comment] 2017-08-23 17:17
@krizhanovsky test waiting in #799 (on top of refactorings), now marked as xfail.

**Comment by ikoveshnikov** [comment] 2017-08-23 20:01
I've reproduced the issue, but the scenario is slightly different. We actually get a crash on parsing the original response:
```
HTTP/1.1 204 No Content
Content-type: text/html
Connection: keep-alive
Content-Length: 138
Last-Modified: Mon, 12 Dec 2016 13:59:39 GMT
Server: Deproxy Server
Date: Wed, 23 Aug 2017 11:56:18 GMT
<html>
<head>
    <title>An Example Page</title>
</head>
<body>
    Hello World, this is a very simple HTML document.
</body>
</html>
```

But the reason is different. Parser says, that response is invalid, since there's no CRLF between headers and body. And we get a crash which is duplicate of #798 . 

But the original issue is caused by other response:
```
HTTP/1.1 204 No Content
Content-type: text/html
Connection: keep-alive
Content-Length: 138
Last-Modified: Mon, 12 Dec 2016 13:59:39 GMT
Server: Deproxy Server
Date: Wed, 23 Aug 2017 11:56:18 GMT

<html>
<head>
    <title>An Example Page</title>
</head>
<body>
    Hello World, this is a very simple HTML document.
</body>
</html>
```
Note the CRLF between headers and body. The response is succesfuly parsed. And we will run into BUG_ON as described above:
https://github.com/tempesta-tech/tempesta/blob/9df1d21d3ea109f8d8b504a28510ff7d348575bd/tempesta_fw/http.c#L2473-L2480

As RFC7231 section-6.3.5 says:
```
A 204 response is terminated by the first empty line after the header
fields because it cannot contain a message body.
```
So the parser will stop right after empty line after the headers, response is fully parsed. But the parser doesn't set `TFW_HTTP_VOID_BODY` flag, and there is non-null `Content-Length` header, so we have to crash on the BUG_ON. I don't know whether 204 response could have `Content-Length` header or not,  this should be checked. 

Probably BUG_ON is too strict assertion here and it could be replaced with `goto bad_msg;`.

**Comment by bartolootrit** [comment] 2017-08-28 18:48
It seems that the same BUG_ON is triggered with another status code:

```
HTTP/1.1 304 Not Modified
Content-type: text/html
Connection: keep-alive
Content-Length: 138
Last-Modified: Mon, 12 Dec 2016 13:59:39 GMT
Server: Deproxy Server
Date: Mon, 28 Aug 2017 18:41:21 GMT

<html>
<head>
  <title>An Example Page</title>
</head>
<body>
  Hello World, this is a very simple HTML document.
</body>
</html>
```

**Comment by ikoveshnikov** [comment] 2017-08-28 19:07
Thank you, @bartolootrit !

Yes, you're right, the same message with 100, 204 or 304 status will cause the issue (Not all of them, are valid though):
https://github.com/tempesta-tech/tempesta/blob/0e55316bd05232985cfa6ae80599e2978b790180/tempesta_fw/http_parser.c#L947-L948

We need to double check with RFC which responses must or may not have the body.

**Closed** 2017-09-05 07:04 UTC
Labels: bug
